export default {
  string: require('./common/string').default,
  text: require('./common/text').default,
  boolean: require('./common/boolean').default,
  integer: require('./common/integer').default,
  decimal: require('./common/decimal').default,
  double: require('./common/double').default,
  time: require('./common/time').default,
  timestamp: require('./common/timestamp').default,
  date: require('./common/date').default,
  now: require('./common/now').default,
  enum: require('./common/enum').default,
  json: require('./common/json').default,
  subtable: require('./common/subtable').default,
  uuid: require('./common/uuid').default,
  structure: require('./common/structure').default,
  refers: require('./common/refers').default,

  nanoid: require('./common/string').default,
  toggle: require('./ud/toggle').default,
  phone: require('./common/string').default,
  refersSelect: require('./ud/refersSelect').default,
  money: require('./ud/money').default,
  email: require('./ud/email').default,
  flatSubtableAsStructure: require('./ud/flatSubtableAsStructure').default,
  password: require('./ud/password').default,
  passwordNoBcrypt: require('./ud/passwordNoBcrypt').default,
  tags: require('./ud/tags').default,
  moneyInteger: require('./ud/moneyInteger').default,
  moneyDouble: require('./ud/moneyDouble').default,
  attachedFiles: require('./ud/attachedFiles').default,
  autocomplete: require('./ud/autocomplete').default,
  autocompleteMultiple: require('./ud/autocompleteMultiple').default,
  englishProficiency: require('./ud/englishProficiency').default,
  experienceTime: require('./ud/experienceTime').default,
  editor: require('./ud/editor').default,
  year: require('./ud/year').default,
}
